# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
# Adapted from: https://github.com/canonical/postgresql-operator/blob/main/.github/workflows/ci.yaml
name: Unit test charm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**.md"
      - ".jujuignore"

jobs:
  unit-test:
    name: Unit test charm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install tox
        run: |
          pipx install tox
      - name: Run tests
        run: tox run -e unit
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - run: make terraform-test
