# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
# Adapted from: https://github.com/canonical/postgresql-operator/blob/main/.github/workflows/ci.yaml
name: Unit test charm

concurrency:
  group: unit-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**.md"
      - ".jujuignore"
  workflow_call:

jobs:
  unit-test:
    name: Unit test charm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests
        run: make test

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - name: Run terraform tests
        run: make terraform-test-all
